### ISSUE TITLE
Helm chart sensitive data 

### ISSUE THREAD

**Issue by kolikons** [kyverno/policy-reporter#14]
Also, I don't like the secret file, you don't encrypt to base64 and some CI can block when you're checking manifest
I'll recomend you replace https://github.com/fjogeleit/policy-reporter/blob/main/charts/policy-reporter/templates/targetssecret.yaml#L8 to use `| b64enc` but it's braking change in helm chart

And one more thing what's about move vars `loki:`,`elasticsearch:` insde additinal object `config.loki`, `config.elasticsearch i`, 
https://github.com/fjogeleit/policy-reporter/blob/b71128448dcbfde8bd2937d4d60661103d9c52c3/charts/policy-reporter/values.yaml#L30

```
helm template ./
---
# Source: policy-reporter/templates/targetssecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: policy-reporter-targets
  labels:
    helm.sh/chart: policy-reporter-0.16.2
    app.kubernetes.io/name: policy-reporter
    app.kubernetes.io/instance: policy-reporter
    app.kubernetes.io/version: "0.12.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  config.yaml: |-
    loki:
      host: ""
      minimumPriority: ""
      skipExistingOnStartup: true

    elasticsearch:
      host: ""
      index: "policy-reporter"
      rotation: "dayli"
      minimumPriority: ""
      skipExistingOnStartup: true

    slack:
      webhook: ""
      minimumPriority: ""
      skipExistingOnStartup: true

    discord:
      webhook: ""
      minimumPriority: ""
      skipExistingOnStartup: true
```
