### ISSUE TITLE
Loki headers not being rendered

### ISSUE THREAD

**Issue by ArjonBu** [kyverno/policy-reporter#604]
Hello, 

I am deploying the helm chart version `3.0.0-rc.10` with Loki target and it doesn't render the `headers` key. 

```
target:
  loki:
    host: "domain.com"
    headers:
      "X-Scope-OrgID": "team-1"
    customFields:
     kyverno: reports
      cluster: cluster1
```

The secret generated does not have the Loki headers.
